modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "sands_of_time.png"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "relics"
type = "required"
versionRange = "[0.10.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "required"
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
